[package]
name = "hermit-rust"
version = "0.1.0"
authors = ["nick <scifi6546@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web="1.0"
serde={version="*", features=["derive"]}
serde_json="*"
